name: Workflow D

on:
  workflow_run:
    workflows: ["Workflow A"]
    types: ["completed"]
    branches: ["main"]

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts from other workflow
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GH_ACTION_TOKEN }}
      - name: List all files
        run: |
          pwd
          ls -lah
