name: Workflow D

on:
  workflow_run:
    workflows: ["Workflow A"]
    types: ["completed"]

jobs:
  download:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # - name: Download artifacts from other workflow
      #   uses: actions/download-artifact@v4
      #   with:
      #     merge-multiple: true
      #     run-id: ${{ github.event.workflow_run.id }}
      #     github-token: ${{ secrets.GH_ACTION_TOKEN }}
      # - name: List all files
      #   run: |
      #     pwd
      #     ls -lah
      - name: echo variables
        run: |
          echo "This is an example branch"
          echo "Event is "
          echo ${{ github.event.workflow_run.event }}
          echo "head branch is "
          echo ${{ github.event.workflow_run.head_branch }}
      - name: echo variables
        if: >-
          ${{ github.event.workflow_run.event == 'push'
          && github.event.workflow_run.head_branch == 'main' }}
        run: |
          echo "This is a push event to the main branch"
